# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Square1_0.0.1.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}
