# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Native Application

on:
  push:
    branches:
      - ci-test

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Maven
        run: mvn clean package -DskipTests

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Maven
        run: mvn clean package -DskipTests

  build-macos-x86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build for x86_64
        run: |
          mkdir -p build/x86_64
          mvn clean package -DskipTests \
            -Djavacpp.platform.name=osx-x86_64 \
            -Dmaven.repo.local=build/x86_64/.m2 \
            -Dos.detected.name=osx-x86_64
      - name: Debug artifact path
        run: ls -la target/deploy/osx-x86_64/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-x86_64
          path: target/deploy/osx-x86_64/*.zip

  build-macos-arm64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build for arm64
        run: |
          mkdir -p build/arm64
          mvn clean package -DskipTests \
            -Djavacpp.platform.name=osx-arm64 \
            -Dmaven.repo.local=build/arm64/.m2 \
            -Dos.detected.name=osx-arm64
      - name: Debug artifact path
        run: ls -la target/deploy/osx-arm64/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-arm64
          path: target/deploy/osx-arm64/*.zip

  create-universal:
    runs-on: macos-13
    needs: [build-macos-x86_64, build-macos-arm64]
    steps:
      - name: Download x86_64 build
        uses: actions/download-artifact@v4
        with:
          name: macos-build-x86_64
          path: build/x86_64

      - name: Download arm64 build
        uses: actions/download-artifact@v4
        with:
          name: macos-build-arm64
          path: build/arm64

      - name: Package both into ZIP
        run: |
          mkdir -p dist
          unzip -o build/x86_64/*.zip -d dist/x86_64
          unzip -o build/arm64/*.zip -d dist/arm64
          zip -r Square1-macOS-universal.zip dist

      - name: Upload macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: macOS-universal-zip
          path: Square1-macOS-universal.zip